services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: benchmark
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres_data:/var/lib/postgresql
    networks:
      - node-1m-rps

  redis:
    image: redis:8.6-alpine
    container_name: redis_cache
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis_data:/data
    networks:
      - node-1m-rps

networks:
  node-1m-rps:
    driver: bridge
